version: '3.8'

services:
  backend:
    build: ./backend 
    container_name: planejador-backend
    ports:
      - "4000:4000" 
    volumes:
      - ./backend:/app 
      - /app/node_modules 
    env_file:
      - ./backend/.env 

  frontend:
    build: ./frontend 
    container_name: planejador-frontend
    ports:
      - "5173:5173" 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:4000/api 
    depends_on:
      - backend 